---
- name: Install wget, java8 & git
  yum:
    name:
      - wget
      - java-1.8.0-openjdk
      - git

- name: Add jenkins.repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins Key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: present
    
- name: Start Jenkins and enable systemd
  systemd:
    name: jenkins
    state: started
    enabled: true

- name: Wait for 30 secs for jenkins to startup
  wait_for: timeout=30

- name: Copy Jenkins initialAdminPassword
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Print Jenkins initialAdminPassword to stdout
  debug:
    var: result.stdout
    
